#!/usr/bin/env bash


### install various flatpak files and appimages
# I work in IT and have various laptops kicking around from former colleagues.
# I will often reinstall them with something linux based - sadly I also have to reinstall windows
# from time to time as well
# I install the same list of apps on every distro and it's just a pain in the arse
# to go to flathub each and every time and install manually
# once click script is the answer.



## Essential Applications
# Slack
flatpak install flathub com.slack.Slack
flatpak install flathub com.vivaldi.Vivaldi
flatpak install flathub com.google.Chrome
flatpak install flathub com.visualstudio.code

## Nice to have applications

flatpak install flathub dev.zed.Zed
flatpak install flathub org.onlyoffice.desktopeditors



## Latest Clickup Appimage
https://desktop.clickup.com/linux?_gl=1*2ziae5*_gcl_au*MTczMTE3MjgxMS4xNzQ3MDUzMjIz



### Essential Tools
# Gear Lever

flatpak install flathub it.mijorus.gearlever


### Nice to have tools
# appl image hub
flatpak install flathub io.github.prateekmedia.appimagepool
